#!/bin/sh
# (c) 2012-09-25, by Wiimm


ln -f ./RetroRewind6/Binaries/Code.pul ./workdir.tmp/files/Binaries/Code.pul
ln -f ./RetroRewind6/Binaries/Config.pul ./workdir.tmp/files/Binaries/Config.pul
ln -f ./RetroRewind6/Binaries/Loader.pul ./workdir.tmp/files/Binaries/Loader.pul
ln -f ./RetroRewind6/Assets/CommonAssets.szs ./workdir.tmp/files/CommonAssets.szs
ln -f ./RetroRewind6/Assets/RaceAssets.szs ./workdir.tmp/files/RaceAssets.szs
ln -f ./RetroRewind6/Assets/UIAssets.szs ./workdir.tmp/files/UIAssets.szs
ln -f ./RetroRewind6/Ghosts/Experts ./workdir.tmp/files/Experts
ln -f ./RetroRewind6/Tracks/0.szs ./workdir.tmp/files/Race/Course/0.szs
ln -f ./RetroRewind6/Tracks/1.szs ./workdir.tmp/files/Race/Course/1.szs
ln -f ./RetroRewind6/Tracks/2.szs ./workdir.tmp/files/Race/Course/2.szs
ln -f ./RetroRewind6/Tracks/3.szs ./workdir.tmp/files/Race/Course/3.szs
ln -f ./RetroRewind6/Tracks/4.szs ./workdir.tmp/files/Race/Course/4.szs
ln -f ./RetroRewind6/Tracks/5.szs ./workdir.tmp/files/Race/Course/5.szs
ln -f ./RetroRewind6/Tracks/6.szs ./workdir.tmp/files/Race/Course/6.szs
ln -f ./RetroRewind6/Tracks/7.szs ./workdir.tmp/files/Race/Course/7.szs
ln -f ./RetroRewind6/Tracks/8.szs ./workdir.tmp/files/Race/Course/8.szs
ln -f ./RetroRewind6/Tracks/9.szs ./workdir.tmp/files/Race/Course/9.szs
ln -f ./RetroRewind6/Tracks/10.szs ./workdir.tmp/files/Race/Course/10.szs
ln -f ./RetroRewind6/Tracks/11.szs ./workdir.tmp/files/Race/Course/11.szs
ln -f ./RetroRewind6/Tracks/12.szs ./workdir.tmp/files/Race/Course/12.szs
ln -f ./RetroRewind6/Tracks/13.szs ./workdir.tmp/files/Race/Course/13.szs
ln -f ./RetroRewind6/Tracks/14.szs ./workdir.tmp/files/Race/Course/14.szs
ln -f ./RetroRewind6/Tracks/15.szs ./workdir.tmp/files/Race/Course/15.szs
ln -f ./RetroRewind6/Tracks/16.szs ./workdir.tmp/files/Race/Course/16.szs
ln -f ./RetroRewind6/Tracks/17.szs ./workdir.tmp/files/Race/Course/17.szs
ln -f ./RetroRewind6/Tracks/18.szs ./workdir.tmp/files/Race/Course/18.szs
ln -f ./RetroRewind6/Tracks/19.szs ./workdir.tmp/files/Race/Course/19.szs
ln -f ./RetroRewind6/Tracks/20.szs ./workdir.tmp/files/Race/Course/20.szs
ln -f ./RetroRewind6/Tracks/21.szs ./workdir.tmp/files/Race/Course/21.szs
ln -f ./RetroRewind6/Tracks/22.szs ./workdir.tmp/files/Race/Course/22.szs
ln -f ./RetroRewind6/Tracks/23.szs ./workdir.tmp/files/Race/Course/23.szs
ln -f ./RetroRewind6/Tracks/24.szs ./workdir.tmp/files/Race/Course/24.szs
ln -f ./RetroRewind6/Tracks/25.szs ./workdir.tmp/files/Race/Course/25.szs
ln -f ./RetroRewind6/Tracks/26.szs ./workdir.tmp/files/Race/Course/26.szs
ln -f ./RetroRewind6/Tracks/27.szs ./workdir.tmp/files/Race/Course/27.szs
ln -f ./RetroRewind6/Tracks/28.szs ./workdir.tmp/files/Race/Course/28.szs
ln -f ./RetroRewind6/Tracks/29.szs ./workdir.tmp/files/Race/Course/29.szs
ln -f ./RetroRewind6/Tracks/30.szs ./workdir.tmp/files/Race/Course/30.szs
ln -f ./RetroRewind6/Tracks/31.szs ./workdir.tmp/files/Race/Course/31.szs
ln -f ./RetroRewind6/Tracks/32.szs ./workdir.tmp/files/Race/Course/32.szs
ln -f ./RetroRewind6/Tracks/33.szs ./workdir.tmp/files/Race/Course/33.szs
ln -f ./RetroRewind6/Tracks/34.szs ./workdir.tmp/files/Race/Course/34.szs
ln -f ./RetroRewind6/Tracks/35.szs ./workdir.tmp/files/Race/Course/35.szs
ln -f ./RetroRewind6/Tracks/36.szs ./workdir.tmp/files/Race/Course/36.szs
ln -f ./RetroRewind6/Tracks/37.szs ./workdir.tmp/files/Race/Course/37.szs
ln -f ./RetroRewind6/Tracks/38.szs ./workdir.tmp/files/Race/Course/38.szs
ln -f ./RetroRewind6/Tracks/39.szs ./workdir.tmp/files/Race/Course/39.szs
ln -f ./RetroRewind6/Tracks/40.szs ./workdir.tmp/files/Race/Course/40.szs
ln -f ./RetroRewind6/Tracks/41.szs ./workdir.tmp/files/Race/Course/41.szs
ln -f ./RetroRewind6/Tracks/42.szs ./workdir.tmp/files/Race/Course/42.szs
ln -f ./RetroRewind6/Tracks/43.szs ./workdir.tmp/files/Race/Course/43.szs
ln -f ./RetroRewind6/Tracks/44.szs ./workdir.tmp/files/Race/Course/44.szs
ln -f ./RetroRewind6/Tracks/45.szs ./workdir.tmp/files/Race/Course/45.szs
ln -f ./RetroRewind6/Tracks/46.szs ./workdir.tmp/files/Race/Course/46.szs
ln -f ./RetroRewind6/Tracks/47.szs ./workdir.tmp/files/Race/Course/47.szs
ln -f ./RetroRewind6/Tracks/48.szs ./workdir.tmp/files/Race/Course/48.szs
ln -f ./RetroRewind6/Tracks/49.szs ./workdir.tmp/files/Race/Course/49.szs
ln -f ./RetroRewind6/Tracks/50.szs ./workdir.tmp/files/Race/Course/50.szs
ln -f ./RetroRewind6/Tracks/51.szs ./workdir.tmp/files/Race/Course/51.szs
ln -f ./RetroRewind6/Tracks/52.szs ./workdir.tmp/files/Race/Course/52.szs
ln -f ./RetroRewind6/Tracks/53.szs ./workdir.tmp/files/Race/Course/53.szs
ln -f ./RetroRewind6/Tracks/54.szs ./workdir.tmp/files/Race/Course/54.szs
ln -f ./RetroRewind6/Tracks/55.szs ./workdir.tmp/files/Race/Course/55.szs
ln -f ./RetroRewind6/Tracks/56.szs ./workdir.tmp/files/Race/Course/56.szs
ln -f ./RetroRewind6/Tracks/57.szs ./workdir.tmp/files/Race/Course/57.szs
ln -f ./RetroRewind6/Tracks/58.szs ./workdir.tmp/files/Race/Course/58.szs
ln -f ./RetroRewind6/Tracks/59.szs ./workdir.tmp/files/Race/Course/59.szs
ln -f ./RetroRewind6/Tracks/60.szs ./workdir.tmp/files/Race/Course/60.szs
ln -f ./RetroRewind6/Tracks/61.szs ./workdir.tmp/files/Race/Course/61.szs
ln -f ./RetroRewind6/Tracks/62.szs ./workdir.tmp/files/Race/Course/62.szs
ln -f ./RetroRewind6/Tracks/63.szs ./workdir.tmp/files/Race/Course/63.szs
ln -f ./RetroRewind6/Tracks/64.szs ./workdir.tmp/files/Race/Course/64.szs
ln -f ./RetroRewind6/Tracks/65.szs ./workdir.tmp/files/Race/Course/65.szs
ln -f ./RetroRewind6/Tracks/66.szs ./workdir.tmp/files/Race/Course/66.szs
ln -f ./RetroRewind6/Tracks/67.szs ./workdir.tmp/files/Race/Course/67.szs
ln -f ./RetroRewind6/Tracks/68.szs ./workdir.tmp/files/Race/Course/68.szs
ln -f ./RetroRewind6/Tracks/69.szs ./workdir.tmp/files/Race/Course/69.szs
ln -f ./RetroRewind6/Tracks/70.szs ./workdir.tmp/files/Race/Course/70.szs
ln -f ./RetroRewind6/Tracks/71.szs ./workdir.tmp/files/Race/Course/71.szs
ln -f ./RetroRewind6/Tracks/72.szs ./workdir.tmp/files/Race/Course/72.szs
ln -f ./RetroRewind6/Tracks/73.szs ./workdir.tmp/files/Race/Course/73.szs
ln -f ./RetroRewind6/Tracks/74.szs ./workdir.tmp/files/Race/Course/74.szs
ln -f ./RetroRewind6/Tracks/75.szs ./workdir.tmp/files/Race/Course/75.szs
ln -f ./RetroRewind6/Tracks/76.szs ./workdir.tmp/files/Race/Course/76.szs
ln -f ./RetroRewind6/Tracks/77.szs ./workdir.tmp/files/Race/Course/77.szs
ln -f ./RetroRewind6/Tracks/78.szs ./workdir.tmp/files/Race/Course/78.szs
ln -f ./RetroRewind6/Tracks/79.szs ./workdir.tmp/files/Race/Course/79.szs
ln -f ./RetroRewind6/Tracks/80.szs ./workdir.tmp/files/Race/Course/80.szs
ln -f ./RetroRewind6/Tracks/81.szs ./workdir.tmp/files/Race/Course/81.szs
ln -f ./RetroRewind6/Tracks/82.szs ./workdir.tmp/files/Race/Course/82.szs
ln -f ./RetroRewind6/Tracks/83.szs ./workdir.tmp/files/Race/Course/83.szs
ln -f ./RetroRewind6/Tracks/84.szs ./workdir.tmp/files/Race/Course/84.szs
ln -f ./RetroRewind6/Tracks/85.szs ./workdir.tmp/files/Race/Course/85.szs
ln -f ./RetroRewind6/Tracks/86.szs ./workdir.tmp/files/Race/Course/86.szs
ln -f ./RetroRewind6/Tracks/87.szs ./workdir.tmp/files/Race/Course/87.szs
ln -f ./RetroRewind6/Tracks/88.szs ./workdir.tmp/files/Race/Course/88.szs
ln -f ./RetroRewind6/Tracks/89.szs ./workdir.tmp/files/Race/Course/89.szs
ln -f ./RetroRewind6/Tracks/90.szs ./workdir.tmp/files/Race/Course/90.szs
ln -f ./RetroRewind6/Tracks/91.szs ./workdir.tmp/files/Race/Course/91.szs
ln -f ./RetroRewind6/Tracks/92.szs ./workdir.tmp/files/Race/Course/92.szs
ln -f ./RetroRewind6/Tracks/93.szs ./workdir.tmp/files/Race/Course/93.szs
ln -f ./RetroRewind6/Tracks/94.szs ./workdir.tmp/files/Race/Course/94.szs
ln -f ./RetroRewind6/Tracks/95.szs ./workdir.tmp/files/Race/Course/95.szs
ln -f ./RetroRewind6/Tracks/96.szs ./workdir.tmp/files/Race/Course/96.szs
ln -f ./RetroRewind6/Tracks/97.szs ./workdir.tmp/files/Race/Course/97.szs
ln -f ./RetroRewind6/Tracks/98.szs ./workdir.tmp/files/Race/Course/98.szs
ln -f ./RetroRewind6/Tracks/99.szs ./workdir.tmp/files/Race/Course/99.szs
ln -f ./RetroRewind6/Tracks/100.szs ./workdir.tmp/files/Race/Course/100.szs
ln -f ./RetroRewind6/Tracks/101.szs ./workdir.tmp/files/Race/Course/101.szs
ln -f ./RetroRewind6/Tracks/102.szs ./workdir.tmp/files/Race/Course/102.szs
ln -f ./RetroRewind6/Tracks/103.szs ./workdir.tmp/files/Race/Course/103.szs
ln -f ./RetroRewind6/Tracks/104.szs ./workdir.tmp/files/Race/Course/104.szs
ln -f ./RetroRewind6/Tracks/105.szs ./workdir.tmp/files/Race/Course/105.szs
ln -f ./RetroRewind6/Tracks/106.szs ./workdir.tmp/files/Race/Course/106.szs
ln -f ./RetroRewind6/Tracks/107.szs ./workdir.tmp/files/Race/Course/107.szs
ln -f ./RetroRewind6/Tracks/108.szs ./workdir.tmp/files/Race/Course/108.szs
ln -f ./RetroRewind6/Tracks/109.szs ./workdir.tmp/files/Race/Course/109.szs
ln -f ./RetroRewind6/Tracks/110.szs ./workdir.tmp/files/Race/Course/110.szs
ln -f ./RetroRewind6/Tracks/111.szs ./workdir.tmp/files/Race/Course/111.szs
ln -f ./RetroRewind6/Tracks/112.szs ./workdir.tmp/files/Race/Course/112.szs
ln -f ./RetroRewind6/Tracks/113.szs ./workdir.tmp/files/Race/Course/113.szs
ln -f ./RetroRewind6/Tracks/114.szs ./workdir.tmp/files/Race/Course/114.szs
ln -f ./RetroRewind6/Tracks/115.szs ./workdir.tmp/files/Race/Course/115.szs
ln -f ./RetroRewind6/Tracks/116.szs ./workdir.tmp/files/Race/Course/116.szs
ln -f ./RetroRewind6/Tracks/117.szs ./workdir.tmp/files/Race/Course/117.szs
ln -f ./RetroRewind6/Tracks/118.szs ./workdir.tmp/files/Race/Course/118.szs
ln -f ./RetroRewind6/Tracks/119.szs ./workdir.tmp/files/Race/Course/119.szs
ln -f ./RetroRewind6/Tracks/uMKS.szs ./workdir.tmp/files/Race/Course/120.szs
ln -f ./RetroRewind6/Tracks/uSSC.szs ./workdir.tmp/files/Race/Course/121.szs
ln -f ./RetroRewind6/Tracks/uTR.szs ./workdir.tmp/files/Race/Course/122.szs
ln -f ./RetroRewind6/Tracks/uMC.szs ./workdir.tmp/files/Race/Course/123.szs
ln -f ./RetroRewind6/Tracks/uTH.szs ./workdir.tmp/files/Race/Course/124.szs
ln -f ./RetroRewind6/Tracks/uTM.szs ./workdir.tmp/files/Race/Course/125.szs
ln -f ./RetroRewind6/Tracks/uSGF.szs ./workdir.tmp/files/Race/Course/126.szs
ln -f ./RetroRewind6/Tracks/uDS.szs ./workdir.tmp/files/Race/Course/127.szs
ln -f ./RetroRewind6/Tracks/uE.szs ./workdir.tmp/files/Race/Course/128.szs
ln -f ./RetroRewind6/Tracks/uMW.szs ./workdir.tmp/files/Race/Course/129.szs
ln -f ./RetroRewind6/Tracks/uCC.szs ./workdir.tmp/files/Race/Course/130.szs
ln -f ./RetroRewind6/Tracks/uBDD.szs ./workdir.tmp/files/Race/Course/131.szs
ln -f ./RetroRewind6/Tracks/uBC.szs ./workdir.tmp/files/Race/Course/132.szs
ln -f ./RetroRewind6/Tracks/uRR.szs ./workdir.tmp/files/Race/Course/133.szs
ln -f ./RetroRewind6/Tracks/urDDD.szs ./workdir.tmp/files/Race/Course/134.szs
ln -f ./RetroRewind6/Tracks/urRR.szs ./workdir.tmp/files/Race/Course/135.szs
ln -f ./RetroRewind6/Tracks/uMuC.szs ./workdir.tmp/files/Race/Course/136.szs
ln -f ./RetroRewind6/Tracks/uEA.szs ./workdir.tmp/files/Race/Course/137.szs
ln -f ./RetroRewind6/Tracks/uHC.szs ./workdir.tmp/files/Race/Course/138.szs
ln -f ./RetroRewind6/Tracks/uCL.szs ./workdir.tmp/files/Race/Course/139.szs
ln -f ./RetroRewind6/Tracks/uWW.szs ./workdir.tmp/files/Race/Course/140.szs
ln -f ./RetroRewind6/Tracks/uAC.szs ./workdir.tmp/files/Race/Course/141.szs
ln -f ./RetroRewind6/Tracks/urRiR.szs ./workdir.tmp/files/Race/Course/142.szs
ln -f ./RetroRewind6/Tracks/uBB.szs ./workdir.tmp/files/Race/Course/143.szs
ln -f ./RetroRewind6/Tracks/sSHS.szs ./workdir.tmp/files/Race/Course/144.szs
ln -f ./RetroRewind6/Tracks/sYI.szs ./workdir.tmp/files/Race/Course/145.szs
ln -f ./RetroRewind6/Tracks/sfcRR.szs ./workdir.tmp/files/Race/Course/146.szs
ln -f ./RetroRewind6/Tracks/gMC.szs ./workdir.tmp/files/Race/Course/147.szs
ln -f ./RetroRewind6/Tracks/tTB.szs ./workdir.tmp/files/Race/Course/148.szs
ln -f ./RetroRewind6/Tracks/tMD.szs ./workdir.tmp/files/Race/Course/149.szs
ln -f ./RetroRewind6/Tracks/tMM.szs ./workdir.tmp/files/Race/Course/150.szs
ln -f ./RetroRewind6/Tracks/tNH.szs ./workdir.tmp/files/Race/Course/151.szs
ln -f ./RetroRewind6/Tracks/rMC1.szs ./workdir.tmp/files/Race/Course/152.szs
ln -f ./RetroRewind6/Tracks/rCI1.szs ./workdir.tmp/files/Race/Course/153.szs
ln -f ./RetroRewind6/Tracks/rRR1.szs ./workdir.tmp/files/Race/Course/154.szs
ln -f ./RetroRewind6/Tracks/rRR2.szs ./workdir.tmp/files/Race/Course/155.szs
ln -f ./RetroRewind6/Tracks/rVL1.szs ./workdir.tmp/files/Race/Course/156.szs
ln -f ./RetroRewind6/Tracks/rVL2.szs ./workdir.tmp/files/Race/Course/157.szs
ln -f ./RetroRewind6/Tracks/rGV1.szs ./workdir.tmp/files/Race/Course/158.szs
ln -f ./RetroRewind6/Tracks/rBC1.szs ./workdir.tmp/files/Race/Course/159.szs
ln -f ./RetroRewind6/Tracks/rDP1.szs ./workdir.tmp/files/Race/Course/160.szs
ln -f ./RetroRewind6/Tracks/trBC3.szs ./workdir.tmp/files/Race/Course/161.szs
ln -f ./RetroRewind6/Tracks/trCM.szs ./workdir.tmp/files/Race/Course/162.szs
ln -f ./RetroRewind6/Tracks/trPC.szs ./workdir.tmp/files/Race/Course/163.szs
ln -f ./RetroRewind6/Tracks/trRP.szs ./workdir.tmp/files/Race/Course/164.szs
ln -f ./RetroRewind6/Tracks/trBL.szs ./workdir.tmp/files/Race/Course/165.szs
ln -f ./RetroRewind6/Tracks/trSG.szs ./workdir.tmp/files/Race/Course/166.szs
ln -f ./RetroRewind6/Tracks/trCCI.szs ./workdir.tmp/files/Race/Course/167.szs
ln -f ./RetroRewind6/Tracks/trSW.szs ./workdir.tmp/files/Race/Course/168.szs
ln -f ./RetroRewind6/Tracks/trSL.szs ./workdir.tmp/files/Race/Course/169.szs
ln -f ./RetroRewind6/Tracks/trLP.szs ./workdir.tmp/files/Race/Course/170.szs
ln -f ./RetroRewind6/Tracks/gpMB.szs ./workdir.tmp/files/Race/Course/171.szs
ln -f ./RetroRewind6/Tracks/gpMH.szs ./workdir.tmp/files/Race/Course/172.szs
ln -f ./RetroRewind6/Tracks/gpBR.szs ./workdir.tmp/files/Race/Course/173.szs
ln -f ./RetroRewind6/Tracks/gpSP.szs ./workdir.tmp/files/Race/Course/174.szs
ln -f ./RetroRewind6/Tracks/gpBC.szs ./workdir.tmp/files/Race/Course/175.szs
ln -f ./RetroRewind6/Tracks/gpCW.szs ./workdir.tmp/files/Race/Course/176.szs
ln -f ./RetroRewind6/Tracks/gpRC.szs ./workdir.tmp/files/Race/Course/177.szs
ln -f ./RetroRewind6/Tracks/sfcDP1.szs ./workdir.tmp/files/Race/Course/178.szs
ln -f ./RetroRewind6/Tracks/sfcDP2.szs ./workdir.tmp/files/Race/Course/179.szs
ln -f ./RetroRewind6/Tracks/dsDS.szs ./workdir.tmp/files/Race/Course/180.szs
ln -f ./RetroRewind6/Tracks/dsDC.szs ./workdir.tmp/files/Race/Course/181.szs
ln -f ./RetroRewind6/Tracks/dsNB.szs ./workdir.tmp/files/Race/Course/182.szs
ln -f ./RetroRewind6/Tracks/wDDR.szs ./workdir.tmp/files/Race/Course/183.szs
ln -f ./RetroRewind6/Tracks/block_battle.szs ./workdir.tmp/files/Race/Course/block_battle.szs
ln -f ./RetroRewind6/Tracks/casino_battle.szs ./workdir.tmp/files/Race/Course/casino_battle.szs
ln -f ./RetroRewind6/Tracks/old_battle3_gba.szs ./workdir.tmp/files/Race/Course/old_battle3_gba.szs
ln -f ./RetroRewind6/Tracks/old_battle4_sfc.szs ./workdir.tmp/files/Race/Course/old_battle4_sfc.szs
ln -f ./RetroRewind6/Tracks/old_CookieLand_gc.szs ./workdir.tmp/files/Race/Course/old_CookieLand_gc.szs
ln -f ./RetroRewind6/Tracks/old_house_ds.szs ./workdir.tmp/files/Race/Course/old_house_ds.szs
ln -f ./RetroRewind6/Tracks/old_matenro_64.szs ./workdir.tmp/files/Race/Course/old_matenro_64.szs
ln -f ./RetroRewind6/Tracks/sand_battle.szs ./workdir.tmp/files/Race/Course/sand_battle.szs
ln -f ./RetroRewind6/Tracks/venice_battle.szs ./workdir.tmp/files/Race/Course/venice_battle.szs
ln -f ./RetroRewind6/Tracks/0.szs ./workdir.tmp/files/Race/Course/0.szs
ln -f ./RetroRewind6/Tracks/1.szs ./workdir.tmp/files/Race/Course/1.szs
ln -f ./RetroRewind6/Tracks/2.szs ./workdir.tmp/files/Race/Course/2.szs
ln -f ./RetroRewind6/Tracks/3.szs ./workdir.tmp/files/Race/Course/3.szs
ln -f ./RetroRewind6/Tracks/4.szs ./workdir.tmp/files/Race/Course/4.szs
ln -f ./RetroRewind6/Tracks/5.szs ./workdir.tmp/files/Race/Course/5.szs
ln -f ./RetroRewind6/Tracks/6.szs ./workdir.tmp/files/Race/Course/6.szs
ln -f ./RetroRewind6/Tracks/7.szs ./workdir.tmp/files/Race/Course/7.szs
ln -f ./RetroRewind6/Tracks/8.szs ./workdir.tmp/files/Race/Course/8.szs
ln -f ./RetroRewind6/Tracks/9.szs ./workdir.tmp/files/Race/Course/9.szs
ln -f ./RetroRewind6/Tracks/10.szs ./workdir.tmp/files/Race/Course/10.szs
ln -f ./RetroRewind6/Tracks/11.szs ./workdir.tmp/files/Race/Course/11.szs
ln -f ./RetroRewind6/Tracks/12.szs ./workdir.tmp/files/Race/Course/12.szs
ln -f ./RetroRewind6/Tracks/13.szs ./workdir.tmp/files/Race/Course/13.szs
ln -f ./RetroRewind6/Tracks/14.szs ./workdir.tmp/files/Race/Course/14.szs
ln -f ./RetroRewind6/Tracks/15.szs ./workdir.tmp/files/Race/Course/15.szs
ln -f ./RetroRewind6/Tracks/16.szs ./workdir.tmp/files/Race/Course/16.szs
ln -f ./RetroRewind6/Tracks/17.szs ./workdir.tmp/files/Race/Course/17.szs
ln -f ./RetroRewind6/Tracks/18.szs ./workdir.tmp/files/Race/Course/18.szs
ln -f ./RetroRewind6/Tracks/19.szs ./workdir.tmp/files/Race/Course/19.szs
ln -f ./RetroRewind6/Tracks/20.szs ./workdir.tmp/files/Race/Course/20.szs
ln -f ./RetroRewind6/Tracks/21.szs ./workdir.tmp/files/Race/Course/21.szs
ln -f ./RetroRewind6/Tracks/22.szs ./workdir.tmp/files/Race/Course/22.szs
ln -f ./RetroRewind6/Tracks/23.szs ./workdir.tmp/files/Race/Course/23.szs
ln -f ./RetroRewind6/Tracks/24.szs ./workdir.tmp/files/Race/Course/24.szs
ln -f ./RetroRewind6/Tracks/25.szs ./workdir.tmp/files/Race/Course/25.szs
ln -f ./RetroRewind6/Tracks/26.szs ./workdir.tmp/files/Race/Course/26.szs
ln -f ./RetroRewind6/Tracks/27.szs ./workdir.tmp/files/Race/Course/27.szs
ln -f ./RetroRewind6/Tracks/28.szs ./workdir.tmp/files/Race/Course/28.szs
ln -f ./RetroRewind6/Tracks/29.szs ./workdir.tmp/files/Race/Course/29.szs
ln -f ./RetroRewind6/Tracks/30.szs ./workdir.tmp/files/Race/Course/30.szs
ln -f ./RetroRewind6/Tracks/31.szs ./workdir.tmp/files/Race/Course/31.szs
ln -f ./RetroRewind6/Tracks/32.szs ./workdir.tmp/files/Race/Course/32.szs
ln -f ./RetroRewind6/Tracks/33.szs ./workdir.tmp/files/Race/Course/33.szs
ln -f ./RetroRewind6/Tracks/34.szs ./workdir.tmp/files/Race/Course/34.szs
ln -f ./RetroRewind6/Tracks/35.szs ./workdir.tmp/files/Race/Course/35.szs
ln -f ./RetroRewind6/Tracks/36.szs ./workdir.tmp/files/Race/Course/36.szs
ln -f ./RetroRewind6/Tracks/37.szs ./workdir.tmp/files/Race/Course/37.szs
ln -f ./RetroRewind6/Tracks/38.szs ./workdir.tmp/files/Race/Course/38.szs
ln -f ./RetroRewind6/Tracks/39.szs ./workdir.tmp/files/Race/Course/39.szs
ln -f ./RetroRewind6/Tracks/40.szs ./workdir.tmp/files/Race/Course/40.szs
ln -f ./RetroRewind6/Tracks/41.szs ./workdir.tmp/files/Race/Course/41.szs
ln -f ./RetroRewind6/Tracks/42.szs ./workdir.tmp/files/Race/Course/42.szs
ln -f ./RetroRewind6/Tracks/43.szs ./workdir.tmp/files/Race/Course/43.szs
ln -f ./RetroRewind6/Tracks/44.szs ./workdir.tmp/files/Race/Course/44.szs
ln -f ./RetroRewind6/Tracks/45.szs ./workdir.tmp/files/Race/Course/45.szs
ln -f ./RetroRewind6/Tracks/46.szs ./workdir.tmp/files/Race/Course/46.szs
ln -f ./RetroRewind6/Tracks/47.szs ./workdir.tmp/files/Race/Course/47.szs
ln -f ./RetroRewind6/Tracks/48.szs ./workdir.tmp/files/Race/Course/48.szs
ln -f ./RetroRewind6/Tracks/49.szs ./workdir.tmp/files/Race/Course/49.szs
ln -f ./RetroRewind6/Tracks/50.szs ./workdir.tmp/files/Race/Course/50.szs
ln -f ./RetroRewind6/Tracks/51.szs ./workdir.tmp/files/Race/Course/51.szs
ln -f ./RetroRewind6/Tracks/52.szs ./workdir.tmp/files/Race/Course/52.szs
ln -f ./RetroRewind6/Tracks/53.szs ./workdir.tmp/files/Race/Course/53.szs
ln -f ./RetroRewind6/Tracks/54.szs ./workdir.tmp/files/Race/Course/54.szs
ln -f ./RetroRewind6/Tracks/55.szs ./workdir.tmp/files/Race/Course/55.szs
ln -f ./RetroRewind6/Tracks/56.szs ./workdir.tmp/files/Race/Course/56.szs
ln -f ./RetroRewind6/Tracks/57.szs ./workdir.tmp/files/Race/Course/57.szs
ln -f ./RetroRewind6/Tracks/58.szs ./workdir.tmp/files/Race/Course/58.szs
ln -f ./RetroRewind6/Tracks/59.szs ./workdir.tmp/files/Race/Course/59.szs
ln -f ./RetroRewind6/Tracks/60.szs ./workdir.tmp/files/Race/Course/60.szs
ln -f ./RetroRewind6/Tracks/61.szs ./workdir.tmp/files/Race/Course/61.szs
ln -f ./RetroRewind6/Tracks/62.szs ./workdir.tmp/files/Race/Course/62.szs
ln -f ./RetroRewind6/Tracks/63.szs ./workdir.tmp/files/Race/Course/63.szs
ln -f ./RetroRewind6/Tracks/64.szs ./workdir.tmp/files/Race/Course/64.szs
ln -f ./RetroRewind6/Tracks/65.szs ./workdir.tmp/files/Race/Course/65.szs
ln -f ./RetroRewind6/Tracks/66.szs ./workdir.tmp/files/Race/Course/66.szs
ln -f ./RetroRewind6/Tracks/67.szs ./workdir.tmp/files/Race/Course/67.szs
ln -f ./RetroRewind6/Tracks/68.szs ./workdir.tmp/files/Race/Course/68.szs
ln -f ./RetroRewind6/Tracks/69.szs ./workdir.tmp/files/Race/Course/69.szs
ln -f ./RetroRewind6/Tracks/70.szs ./workdir.tmp/files/Race/Course/70.szs
ln -f ./RetroRewind6/Tracks/71.szs ./workdir.tmp/files/Race/Course/71.szs
ln -f ./RetroRewind6/Tracks/72.szs ./workdir.tmp/files/Race/Course/72.szs
ln -f ./RetroRewind6/Tracks/73.szs ./workdir.tmp/files/Race/Course/73.szs
ln -f ./RetroRewind6/Tracks/74.szs ./workdir.tmp/files/Race/Course/74.szs
ln -f ./RetroRewind6/Tracks/75.szs ./workdir.tmp/files/Race/Course/75.szs
ln -f ./RetroRewind6/Tracks/76.szs ./workdir.tmp/files/Race/Course/76.szs
ln -f ./RetroRewind6/Tracks/77.szs ./workdir.tmp/files/Race/Course/77.szs
ln -f ./RetroRewind6/Tracks/78.szs ./workdir.tmp/files/Race/Course/78.szs
ln -f ./RetroRewind6/Tracks/79.szs ./workdir.tmp/files/Race/Course/79.szs
ln -f ./RetroRewind6/Tracks/80.szs ./workdir.tmp/files/Race/Course/80.szs
ln -f ./RetroRewind6/Tracks/81.szs ./workdir.tmp/files/Race/Course/81.szs
ln -f ./RetroRewind6/Tracks/82.szs ./workdir.tmp/files/Race/Course/82.szs
ln -f ./RetroRewind6/Tracks/83.szs ./workdir.tmp/files/Race/Course/83.szs
ln -f ./RetroRewind6/Tracks/84.szs ./workdir.tmp/files/Race/Course/84.szs
ln -f ./RetroRewind6/Tracks/85.szs ./workdir.tmp/files/Race/Course/85.szs
ln -f ./RetroRewind6/Tracks/86.szs ./workdir.tmp/files/Race/Course/86.szs
ln -f ./RetroRewind6/Tracks/87.szs ./workdir.tmp/files/Race/Course/87.szs
ln -f ./RetroRewind6/Tracks/88.szs ./workdir.tmp/files/Race/Course/88.szs
ln -f ./RetroRewind6/Tracks/89.szs ./workdir.tmp/files/Race/Course/89.szs
ln -f ./RetroRewind6/Tracks/90.szs ./workdir.tmp/files/Race/Course/90.szs
ln -f ./RetroRewind6/Tracks/91.szs ./workdir.tmp/files/Race/Course/91.szs
ln -f ./RetroRewind6/Tracks/92.szs ./workdir.tmp/files/Race/Course/92.szs
ln -f ./RetroRewind6/Tracks/93.szs ./workdir.tmp/files/Race/Course/93.szs
ln -f ./RetroRewind6/Tracks/94.szs ./workdir.tmp/files/Race/Course/94.szs
ln -f ./RetroRewind6/Tracks/95.szs ./workdir.tmp/files/Race/Course/95.szs
ln -f ./RetroRewind6/Tracks/96.szs ./workdir.tmp/files/Race/Course/96.szs
ln -f ./RetroRewind6/Tracks/97.szs ./workdir.tmp/files/Race/Course/97.szs
ln -f ./RetroRewind6/Tracks/98.szs ./workdir.tmp/files/Race/Course/98.szs
ln -f ./RetroRewind6/Tracks/99.szs ./workdir.tmp/files/Race/Course/99.szs
ln -f ./RetroRewind6/Tracks/100.szs ./workdir.tmp/files/Race/Course/100.szs
ln -f ./RetroRewind6/Tracks/101.szs ./workdir.tmp/files/Race/Course/101.szs
ln -f ./RetroRewind6/Tracks/102.szs ./workdir.tmp/files/Race/Course/102.szs
ln -f ./RetroRewind6/Tracks/103.szs ./workdir.tmp/files/Race/Course/103.szs
ln -f ./RetroRewind6/Tracks/104.szs ./workdir.tmp/files/Race/Course/104.szs
ln -f ./RetroRewind6/Tracks/105.szs ./workdir.tmp/files/Race/Course/105.szs
ln -f ./RetroRewind6/Tracks/106.szs ./workdir.tmp/files/Race/Course/106.szs
ln -f ./RetroRewind6/Tracks/107.szs ./workdir.tmp/files/Race/Course/107.szs
ln -f ./RetroRewind6/Tracks/108.szs ./workdir.tmp/files/Race/Course/108.szs
ln -f ./RetroRewind6/Tracks/109.szs ./workdir.tmp/files/Race/Course/109.szs
ln -f ./RetroRewind6/Tracks/110.szs ./workdir.tmp/files/Race/Course/110.szs
ln -f ./RetroRewind6/Tracks/111.szs ./workdir.tmp/files/Race/Course/111.szs
ln -f ./RetroRewind6/Tracks/112.szs ./workdir.tmp/files/Race/Course/112.szs
ln -f ./RetroRewind6/Tracks/113.szs ./workdir.tmp/files/Race/Course/113.szs
ln -f ./RetroRewind6/Tracks/114.szs ./workdir.tmp/files/Race/Course/114.szs
ln -f ./RetroRewind6/Tracks/115.szs ./workdir.tmp/files/Race/Course/115.szs
ln -f ./RetroRewind6/Tracks/116.szs ./workdir.tmp/files/Race/Course/116.szs
ln -f ./RetroRewind6/Tracks/117.szs ./workdir.tmp/files/Race/Course/117.szs
ln -f ./RetroRewind6/Tracks/118.szs ./workdir.tmp/files/Race/Course/118.szs
ln -f ./RetroRewind6/Tracks/119.szs ./workdir.tmp/files/Race/Course/119.szs
ln -f ./RetroRewind6/Tracks/uMKS.szs ./workdir.tmp/files/Race/Course/120.szs
ln -f ./RetroRewind6/Tracks/uSSC.szs ./workdir.tmp/files/Race/Course/121.szs
ln -f ./RetroRewind6/Tracks/uTR.szs ./workdir.tmp/files/Race/Course/122.szs
ln -f ./RetroRewind6/Tracks/uMC.szs ./workdir.tmp/files/Race/Course/123.szs
ln -f ./RetroRewind6/Tracks/uTH.szs ./workdir.tmp/files/Race/Course/124.szs
ln -f ./RetroRewind6/Tracks/uTM.szs ./workdir.tmp/files/Race/Course/125.szs
ln -f ./RetroRewind6/Tracks/uSGF.szs ./workdir.tmp/files/Race/Course/126.szs
ln -f ./RetroRewind6/Tracks/uDS.szs ./workdir.tmp/files/Race/Course/127.szs
ln -f ./RetroRewind6/Tracks/uE.szs ./workdir.tmp/files/Race/Course/128.szs
ln -f ./RetroRewind6/Tracks/uMW.szs ./workdir.tmp/files/Race/Course/129.szs
ln -f ./RetroRewind6/Tracks/uCC.szs ./workdir.tmp/files/Race/Course/130.szs
ln -f ./RetroRewind6/Tracks/uBDD.szs ./workdir.tmp/files/Race/Course/131.szs
ln -f ./RetroRewind6/Tracks/uBC.szs ./workdir.tmp/files/Race/Course/132.szs
ln -f ./RetroRewind6/Tracks/uRR.szs ./workdir.tmp/files/Race/Course/133.szs
ln -f ./RetroRewind6/Tracks/urDDD.szs ./workdir.tmp/files/Race/Course/134.szs
ln -f ./RetroRewind6/Tracks/urRR.szs ./workdir.tmp/files/Race/Course/135.szs
ln -f ./RetroRewind6/Tracks/uMuC.szs ./workdir.tmp/files/Race/Course/136.szs
ln -f ./RetroRewind6/Tracks/uEA.szs ./workdir.tmp/files/Race/Course/137.szs
ln -f ./RetroRewind6/Tracks/uHC.szs ./workdir.tmp/files/Race/Course/138.szs
ln -f ./RetroRewind6/Tracks/uCL.szs ./workdir.tmp/files/Race/Course/139.szs
ln -f ./RetroRewind6/Tracks/uWW.szs ./workdir.tmp/files/Race/Course/140.szs
ln -f ./RetroRewind6/Tracks/uAC.szs ./workdir.tmp/files/Race/Course/141.szs
ln -f ./RetroRewind6/Tracks/urRiR.szs ./workdir.tmp/files/Race/Course/142.szs
ln -f ./RetroRewind6/Tracks/uBB.szs ./workdir.tmp/files/Race/Course/143.szs
ln -f ./RetroRewind6/Tracks/sSHS.szs ./workdir.tmp/files/Race/Course/144.szs
ln -f ./RetroRewind6/Tracks/sYI.szs ./workdir.tmp/files/Race/Course/145.szs
ln -f ./RetroRewind6/Tracks/sfcRR.szs ./workdir.tmp/files/Race/Course/146.szs
ln -f ./RetroRewind6/Tracks/gMC.szs ./workdir.tmp/files/Race/Course/147.szs
ln -f ./RetroRewind6/Tracks/tTB.szs ./workdir.tmp/files/Race/Course/148.szs
ln -f ./RetroRewind6/Tracks/tMD.szs ./workdir.tmp/files/Race/Course/149.szs
ln -f ./RetroRewind6/Tracks/tMM.szs ./workdir.tmp/files/Race/Course/150.szs
ln -f ./RetroRewind6/Tracks/tNH.szs ./workdir.tmp/files/Race/Course/151.szs
ln -f ./RetroRewind6/Tracks/rMC1.szs ./workdir.tmp/files/Race/Course/152.szs
ln -f ./RetroRewind6/Tracks/rCI1.szs ./workdir.tmp/files/Race/Course/153.szs
ln -f ./RetroRewind6/Tracks/rRR1.szs ./workdir.tmp/files/Race/Course/154.szs
ln -f ./RetroRewind6/Tracks/rRR2.szs ./workdir.tmp/files/Race/Course/155.szs
ln -f ./RetroRewind6/Tracks/rVL1.szs ./workdir.tmp/files/Race/Course/156.szs
ln -f ./RetroRewind6/Tracks/rVL2.szs ./workdir.tmp/files/Race/Course/157.szs
ln -f ./RetroRewind6/Tracks/rGV1.szs ./workdir.tmp/files/Race/Course/158.szs
ln -f ./RetroRewind6/Tracks/rBC1.szs ./workdir.tmp/files/Race/Course/159.szs
ln -f ./RetroRewind6/Tracks/rDP1.szs ./workdir.tmp/files/Race/Course/160.szs
ln -f ./RetroRewind6/Tracks/trBC3.szs ./workdir.tmp/files/Race/Course/161.szs
ln -f ./RetroRewind6/Tracks/trCM.szs ./workdir.tmp/files/Race/Course/162.szs
ln -f ./RetroRewind6/Tracks/trPC.szs ./workdir.tmp/files/Race/Course/163.szs
ln -f ./RetroRewind6/Tracks/trRP.szs ./workdir.tmp/files/Race/Course/164.szs
ln -f ./RetroRewind6/Tracks/trBL.szs ./workdir.tmp/files/Race/Course/165.szs
ln -f ./RetroRewind6/Tracks/trSG.szs ./workdir.tmp/files/Race/Course/166.szs
ln -f ./RetroRewind6/Tracks/trCCI.szs ./workdir.tmp/files/Race/Course/167.szs
ln -f ./RetroRewind6/Tracks/trSW.szs ./workdir.tmp/files/Race/Course/168.szs
ln -f ./RetroRewind6/Tracks/trSL.szs ./workdir.tmp/files/Race/Course/169.szs
ln -f ./RetroRewind6/Tracks/trLP.szs ./workdir.tmp/files/Race/Course/170.szs
ln -f ./RetroRewind6/Tracks/gpMB.szs ./workdir.tmp/files/Race/Course/171.szs
ln -f ./RetroRewind6/Tracks/gpMH.szs ./workdir.tmp/files/Race/Course/172.szs
ln -f ./RetroRewind6/Tracks/gpBR.szs ./workdir.tmp/files/Race/Course/173.szs
ln -f ./RetroRewind6/Tracks/gpSP.szs ./workdir.tmp/files/Race/Course/174.szs
ln -f ./RetroRewind6/Tracks/gpBC.szs ./workdir.tmp/files/Race/Course/175.szs
ln -f ./RetroRewind6/Tracks/gpCW.szs ./workdir.tmp/files/Race/Course/176.szs
ln -f ./RetroRewind6/Tracks/gpRC.szs ./workdir.tmp/files/Race/Course/177.szs
ln -f ./RetroRewind6/Tracks/sfcDP1.szs ./workdir.tmp/files/Race/Course/178.szs
ln -f ./RetroRewind6/Tracks/sfcDP2.szs ./workdir.tmp/files/Race/Course/179.szs
ln -f ./RetroRewind6/Tracks/dsDS.szs ./workdir.tmp/files/Race/Course/180.szs
ln -f ./RetroRewind6/Tracks/dsDC.szs ./workdir.tmp/files/Race/Course/181.szs
ln -f ./RetroRewind6/Tracks/dsNB.szs ./workdir.tmp/files/Race/Course/182.szs
ln -f ./RetroRewind6/Tracks/wDDR.szs ./workdir.tmp/files/Race/Course/183.szs
ln -f ./RetroRewind6/strm/0_N.brstm ./workdir.tmp/files/sound/strm/0_N.brstm
ln -f ./RetroRewind6/strm/1_N.brstm ./workdir.tmp/files/sound/strm/1_N.brstm
ln -f ./RetroRewind6/strm/2_N.brstm ./workdir.tmp/files/sound/strm/2_N.brstm
ln -f ./RetroRewind6/strm/3_N.brstm ./workdir.tmp/files/sound/strm/3_N.brstm
ln -f ./RetroRewind6/strm/4_N.brstm ./workdir.tmp/files/sound/strm/4_N.brstm
ln -f ./RetroRewind6/strm/5_N.brstm ./workdir.tmp/files/sound/strm/5_N.brstm
ln -f ./RetroRewind6/strm/7_N.brstm ./workdir.tmp/files/sound/strm/7_N.brstm
ln -f ./RetroRewind6/strm/8_N.brstm ./workdir.tmp/files/sound/strm/8_N.brstm
ln -f ./RetroRewind6/strm/10_N.brstm ./workdir.tmp/files/sound/strm/10_N.brstm
ln -f ./RetroRewind6/strm/11_N.brstm ./workdir.tmp/files/sound/strm/11_N.brstm
ln -f ./RetroRewind6/strm/12_N.brstm ./workdir.tmp/files/sound/strm/12_N.brstm
ln -f ./RetroRewind6/strm/13_N.brstm ./workdir.tmp/files/sound/strm/13_N.brstm
ln -f ./RetroRewind6/strm/14_N.brstm ./workdir.tmp/files/sound/strm/14_N.brstm
ln -f ./RetroRewind6/strm/15_N.brstm ./workdir.tmp/files/sound/strm/15_N.brstm
ln -f ./RetroRewind6/strm/16_N.brstm ./workdir.tmp/files/sound/strm/16_N.brstm
ln -f ./RetroRewind6/strm/17_N.brstm ./workdir.tmp/files/sound/strm/17_N.brstm
ln -f ./RetroRewind6/strm/18_N.brstm ./workdir.tmp/files/sound/strm/18_N.brstm
ln -f ./RetroRewind6/strm/19_N.brstm ./workdir.tmp/files/sound/strm/19_N.brstm
ln -f ./RetroRewind6/strm/20_N.brstm ./workdir.tmp/files/sound/strm/20_N.brstm
ln -f ./RetroRewind6/strm/21_N.brstm ./workdir.tmp/files/sound/strm/21_N.brstm
ln -f ./RetroRewind6/strm/22_N.brstm ./workdir.tmp/files/sound/strm/22_N.brstm
ln -f ./RetroRewind6/strm/23_N.brstm ./workdir.tmp/files/sound/strm/23_N.brstm
ln -f ./RetroRewind6/strm/24_N.brstm ./workdir.tmp/files/sound/strm/24_N.brstm
ln -f ./RetroRewind6/strm/25_N.brstm ./workdir.tmp/files/sound/strm/25_N.brstm
ln -f ./RetroRewind6/strm/26_N.brstm ./workdir.tmp/files/sound/strm/26_N.brstm
ln -f ./RetroRewind6/strm/28_N.brstm ./workdir.tmp/files/sound/strm/28_N.brstm
ln -f ./RetroRewind6/strm/30_N.brstm ./workdir.tmp/files/sound/strm/30_N.brstm
ln -f ./RetroRewind6/strm/33_N.brstm ./workdir.tmp/files/sound/strm/33_N.brstm
ln -f ./RetroRewind6/strm/34_N.brstm ./workdir.tmp/files/sound/strm/34_N.brstm
ln -f ./RetroRewind6/strm/35_N.brstm ./workdir.tmp/files/sound/strm/35_N.brstm
ln -f ./RetroRewind6/strm/36_N.brstm ./workdir.tmp/files/sound/strm/36_N.brstm
ln -f ./RetroRewind6/strm/38_N.brstm ./workdir.tmp/files/sound/strm/38_N.brstm
ln -f ./RetroRewind6/strm/39_N.brstm ./workdir.tmp/files/sound/strm/39_N.brstm
ln -f ./RetroRewind6/strm/40_N.brstm ./workdir.tmp/files/sound/strm/40_N.brstm
ln -f ./RetroRewind6/strm/41_N.brstm ./workdir.tmp/files/sound/strm/41_N.brstm
ln -f ./RetroRewind6/strm/42_N.brstm ./workdir.tmp/files/sound/strm/42_N.brstm
ln -f ./RetroRewind6/strm/43_N.brstm ./workdir.tmp/files/sound/strm/43_N.brstm
ln -f ./RetroRewind6/strm/44_N.brstm ./workdir.tmp/files/sound/strm/44_N.brstm
ln -f ./RetroRewind6/strm/45_N.brstm ./workdir.tmp/files/sound/strm/45_N.brstm
ln -f ./RetroRewind6/strm/46_N.brstm ./workdir.tmp/files/sound/strm/46_N.brstm
ln -f ./RetroRewind6/strm/47_N.brstm ./workdir.tmp/files/sound/strm/47_N.brstm
ln -f ./RetroRewind6/strm/48_N.brstm ./workdir.tmp/files/sound/strm/48_N.brstm
ln -f ./RetroRewind6/strm/49_N.brstm ./workdir.tmp/files/sound/strm/49_N.brstm
ln -f ./RetroRewind6/strm/50_N.brstm ./workdir.tmp/files/sound/strm/50_N.brstm
ln -f ./RetroRewind6/strm/52_N.brstm ./workdir.tmp/files/sound/strm/52_N.brstm
ln -f ./RetroRewind6/strm/53_N.brstm ./workdir.tmp/files/sound/strm/53_N.brstm
ln -f ./RetroRewind6/strm/54_N.brstm ./workdir.tmp/files/sound/strm/54_N.brstm
ln -f ./RetroRewind6/strm/55_N.brstm ./workdir.tmp/files/sound/strm/55_N.brstm
ln -f ./RetroRewind6/strm/56_N.brstm ./workdir.tmp/files/sound/strm/56_N.brstm
ln -f ./RetroRewind6/strm/58_N.brstm ./workdir.tmp/files/sound/strm/58_N.brstm
ln -f ./RetroRewind6/strm/59_N.brstm ./workdir.tmp/files/sound/strm/59_N.brstm
ln -f ./RetroRewind6/strm/60_N.brstm ./workdir.tmp/files/sound/strm/60_N.brstm
ln -f ./RetroRewind6/strm/62_N.brstm ./workdir.tmp/files/sound/strm/62_N.brstm
ln -f ./RetroRewind6/strm/64_N.brstm ./workdir.tmp/files/sound/strm/64_N.brstm
ln -f ./RetroRewind6/strm/65_N.brstm ./workdir.tmp/files/sound/strm/65_N.brstm
ln -f ./RetroRewind6/strm/66_N.brstm ./workdir.tmp/files/sound/strm/66_N.brstm
ln -f ./RetroRewind6/strm/68_N.brstm ./workdir.tmp/files/sound/strm/68_N.brstm
ln -f ./RetroRewind6/strm/69_N.brstm ./workdir.tmp/files/sound/strm/69_N.brstm
ln -f ./RetroRewind6/strm/70_N.brstm ./workdir.tmp/files/sound/strm/70_N.brstm
ln -f ./RetroRewind6/strm/71_N.brstm ./workdir.tmp/files/sound/strm/71_N.brstm
ln -f ./RetroRewind6/strm/72_N.brstm ./workdir.tmp/files/sound/strm/72_N.brstm
ln -f ./RetroRewind6/strm/74_N.brstm ./workdir.tmp/files/sound/strm/74_N.brstm
ln -f ./RetroRewind6/strm/75_N.brstm ./workdir.tmp/files/sound/strm/75_N.brstm
ln -f ./RetroRewind6/strm/78_N.brstm ./workdir.tmp/files/sound/strm/78_N.brstm
ln -f ./RetroRewind6/strm/79_N.brstm ./workdir.tmp/files/sound/strm/79_N.brstm
ln -f ./RetroRewind6/strm/80_N.brstm ./workdir.tmp/files/sound/strm/80_N.brstm
ln -f ./RetroRewind6/strm/81_N.brstm ./workdir.tmp/files/sound/strm/81_N.brstm
ln -f ./RetroRewind6/strm/82_N.brstm ./workdir.tmp/files/sound/strm/82_N.brstm
ln -f ./RetroRewind6/strm/83_N.brstm ./workdir.tmp/files/sound/strm/83_N.brstm
ln -f ./RetroRewind6/strm/84_N.brstm ./workdir.tmp/files/sound/strm/84_N.brstm
ln -f ./RetroRewind6/strm/86_N.brstm ./workdir.tmp/files/sound/strm/86_N.brstm
ln -f ./RetroRewind6/strm/87_N.brstm ./workdir.tmp/files/sound/strm/87_N.brstm
ln -f ./RetroRewind6/strm/104_N.brstm ./workdir.tmp/files/sound/strm/104_N.brstm
ln -f ./RetroRewind6/strm/105_N.brstm ./workdir.tmp/files/sound/strm/105_N.brstm
ln -f ./RetroRewind6/strm/106_N.brstm ./workdir.tmp/files/sound/strm/106_N.brstm
ln -f ./RetroRewind6/strm/107_N.brstm ./workdir.tmp/files/sound/strm/107_N.brstm
ln -f ./RetroRewind6/strm/108_N.brstm ./workdir.tmp/files/sound/strm/108_N.brstm
ln -f ./RetroRewind6/strm/109_N.brstm ./workdir.tmp/files/sound/strm/109_N.brstm
ln -f ./RetroRewind6/strm/110_N.brstm ./workdir.tmp/files/sound/strm/110_N.brstm
ln -f ./RetroRewind6/strm/111_N.brstm ./workdir.tmp/files/sound/strm/111_N.brstm
ln -f ./RetroRewind6/strm/112_N.brstm ./workdir.tmp/files/sound/strm/112_N.brstm
ln -f ./RetroRewind6/strm/113_N.brstm ./workdir.tmp/files/sound/strm/113_N.brstm
ln -f ./RetroRewind6/strm/114_N.brstm ./workdir.tmp/files/sound/strm/114_N.brstm
ln -f ./RetroRewind6/strm/115_N.brstm ./workdir.tmp/files/sound/strm/115_N.brstm
ln -f ./RetroRewind6/strm/116_N.brstm ./workdir.tmp/files/sound/strm/116_N.brstm
ln -f ./RetroRewind6/strm/117_N.brstm ./workdir.tmp/files/sound/strm/117_N.brstm
ln -f ./RetroRewind6/strm/118_N.brstm ./workdir.tmp/files/sound/strm/118_N.brstm
ln -f ./RetroRewind6/strm/119_N.brstm ./workdir.tmp/files/sound/strm/119_N.brstm
ln -f ./RetroRewind6/strm/uMKS_N.brstm ./workdir.tmp/files/sound/strm/120_N.brstm
ln -f ./RetroRewind6/strm/uSSC_N.brstm ./workdir.tmp/files/sound/strm/121_N.brstm
ln -f ./RetroRewind6/strm/uTR_N.brstm ./workdir.tmp/files/sound/strm/122_N.brstm
ln -f ./RetroRewind6/strm/uMC_N.brstm ./workdir.tmp/files/sound/strm/123_N.brstm
ln -f ./RetroRewind6/strm/uTH_N.brstm ./workdir.tmp/files/sound/strm/124_N.brstm
ln -f ./RetroRewind6/strm/uTM_N.brstm ./workdir.tmp/files/sound/strm/125_N.brstm
ln -f ./RetroRewind6/strm/uSGF_N.brstm ./workdir.tmp/files/sound/strm/126_N.brstm
ln -f ./RetroRewind6/strm/uDS_N.brstm ./workdir.tmp/files/sound/strm/127_N.brstm
ln -f ./RetroRewind6/strm/uE_N.brstm ./workdir.tmp/files/sound/strm/128_N.brstm
ln -f ./RetroRewind6/strm/uMW_N.brstm ./workdir.tmp/files/sound/strm/129_N.brstm
ln -f ./RetroRewind6/strm/uCC_N.brstm ./workdir.tmp/files/sound/strm/130_N.brstm
ln -f ./RetroRewind6/strm/uBDD_N.brstm ./workdir.tmp/files/sound/strm/131_N.brstm
ln -f ./RetroRewind6/strm/uBC_N.brstm ./workdir.tmp/files/sound/strm/132_N.brstm
ln -f ./RetroRewind6/strm/uRR_N.brstm ./workdir.tmp/files/sound/strm/133_N.brstm
ln -f ./RetroRewind6/strm/urDDD_N.brstm ./workdir.tmp/files/sound/strm/134_N.brstm
ln -f ./RetroRewind6/strm/urRR_N.brstm ./workdir.tmp/files/sound/strm/135_N.brstm
ln -f ./RetroRewind6/strm/uMuC_N.brstm ./workdir.tmp/files/sound/strm/136_N.brstm
ln -f ./RetroRewind6/strm/uEA_N.brstm ./workdir.tmp/files/sound/strm/137_N.brstm
ln -f ./RetroRewind6/strm/uHC_N.brstm ./workdir.tmp/files/sound/strm/138_N.brstm
ln -f ./RetroRewind6/strm/uCL_N.brstm ./workdir.tmp/files/sound/strm/139_N.brstm
ln -f ./RetroRewind6/strm/uWW_N.brstm ./workdir.tmp/files/sound/strm/140_N.brstm
ln -f ./RetroRewind6/strm/uAC_N.brstm ./workdir.tmp/files/sound/strm/141_N.brstm
ln -f ./RetroRewind6/strm/urRiR_N.brstm ./workdir.tmp/files/sound/strm/142_N.brstm
ln -f ./RetroRewind6/strm/uBB_N.brstm ./workdir.tmp/files/sound/strm/143_N.brstm
ln -f ./RetroRewind6/strm/sSHS_N.brstm ./workdir.tmp/files/sound/strm/144_N.brstm
ln -f ./RetroRewind6/strm/sYI_N.brstm ./workdir.tmp/files/sound/strm/145_N.brstm
ln -f ./RetroRewind6/strm/sfcRR_N.brstm ./workdir.tmp/files/sound/strm/146_N.brstm
ln -f ./RetroRewind6/strm/gMC_N.brstm ./workdir.tmp/files/sound/strm/147_N.brstm
ln -f ./RetroRewind6/strm/tTB_N.brstm ./workdir.tmp/files/sound/strm/148_N.brstm
ln -f ./RetroRewind6/strm/tMD_N.brstm ./workdir.tmp/files/sound/strm/149_N.brstm
ln -f ./RetroRewind6/strm/tMM_N.brstm ./workdir.tmp/files/sound/strm/150_N.brstm
ln -f ./RetroRewind6/strm/tNH_N.brstm ./workdir.tmp/files/sound/strm/151_N.brstm
ln -f ./RetroRewind6/strm/rMC1_N.brstm ./workdir.tmp/files/sound/strm/152_N.brstm
ln -f ./RetroRewind6/strm/rCI1_N.brstm ./workdir.tmp/files/sound/strm/153_N.brstm
ln -f ./RetroRewind6/strm/rRR1_N.brstm ./workdir.tmp/files/sound/strm/154_N.brstm
ln -f ./RetroRewind6/strm/rRR2_N.brstm ./workdir.tmp/files/sound/strm/155_N.brstm
ln -f ./RetroRewind6/strm/rVL1_N.brstm ./workdir.tmp/files/sound/strm/156_N.brstm
ln -f ./RetroRewind6/strm/rVL2_N.brstm ./workdir.tmp/files/sound/strm/157_N.brstm
ln -f ./RetroRewind6/strm/rGV1_N.brstm ./workdir.tmp/files/sound/strm/158_N.brstm
ln -f ./RetroRewind6/strm/rBC1_N.brstm ./workdir.tmp/files/sound/strm/159_N.brstm
ln -f ./RetroRewind6/strm/rDP1_N.brstm ./workdir.tmp/files/sound/strm/160_N.brstm
ln -f ./RetroRewind6/strm/trBC3_N.brstm ./workdir.tmp/files/sound/strm/161_N.brstm
ln -f ./RetroRewind6/strm/trCM_N.brstm ./workdir.tmp/files/sound/strm/162_N.brstm
ln -f ./RetroRewind6/strm/trPC_N.brstm ./workdir.tmp/files/sound/strm/163_N.brstm
ln -f ./RetroRewind6/strm/trRP_N.brstm ./workdir.tmp/files/sound/strm/164_N.brstm
ln -f ./RetroRewind6/strm/trBL_N.brstm ./workdir.tmp/files/sound/strm/165_N.brstm
ln -f ./RetroRewind6/strm/trSG_N.brstm ./workdir.tmp/files/sound/strm/166_N.brstm
ln -f ./RetroRewind6/strm/trCCI_N.brstm ./workdir.tmp/files/sound/strm/167_N.brstm
ln -f ./RetroRewind6/strm/trSW_N.brstm ./workdir.tmp/files/sound/strm/168_N.brstm
ln -f ./RetroRewind6/strm/trSL_N.brstm ./workdir.tmp/files/sound/strm/169_N.brstm
ln -f ./RetroRewind6/strm/trLP_N.brstm ./workdir.tmp/files/sound/strm/170_N.brstm
ln -f ./RetroRewind6/strm/gpMB_N.brstm ./workdir.tmp/files/sound/strm/171_N.brstm
ln -f ./RetroRewind6/strm/gpMH_N.brstm ./workdir.tmp/files/sound/strm/172_N.brstm
ln -f ./RetroRewind6/strm/gpBR_N.brstm ./workdir.tmp/files/sound/strm/173_N.brstm
ln -f ./RetroRewind6/strm/gpSP_N.brstm ./workdir.tmp/files/sound/strm/174_N.brstm
ln -f ./RetroRewind6/strm/gpBC_N.brstm ./workdir.tmp/files/sound/strm/175_N.brstm
ln -f ./RetroRewind6/strm/gpCW_N.brstm ./workdir.tmp/files/sound/strm/176_N.brstm
ln -f ./RetroRewind6/strm/gpRC_N.brstm ./workdir.tmp/files/sound/strm/177_N.brstm
ln -f ./RetroRewind6/strm/sfcDP1_N.brstm ./workdir.tmp/files/sound/strm/178_N.brstm
ln -f ./RetroRewind6/strm/sfcDP2_N.brstm ./workdir.tmp/files/sound/strm/179_N.brstm
ln -f ./RetroRewind6/strm/dsDS_N.brstm ./workdir.tmp/files/sound/strm/180_N.brstm
ln -f ./RetroRewind6/strm/dsDC_N.brstm ./workdir.tmp/files/sound/strm/181_N.brstm
ln -f ./RetroRewind6/strm/dsNB_N.brstm ./workdir.tmp/files/sound/strm/182_N.brstm
ln -f ./RetroRewind6/strm/wDDR_N.brstm ./workdir.tmp/files/sound/strm/183_N.brstm
ln -f ./RetroRewind6/strm/sfcMC1_N.brstm ./workdir.tmp/files/sound/strm/265_N.brstm
ln -f ./RetroRewind6/strm/sfcVL2_N.brstm ./workdir.tmp/files/sound/strm/266_N.brstm
ln -f ./RetroRewind6/strm/n64BD_N.brstm ./workdir.tmp/files/sound/strm/267_N.brstm
ln -f ./RetroRewind6/strm/n64BF_N.brstm ./workdir.tmp/files/sound/strm/268_N.brstm
ln -f ./RetroRewind6/strm/n64BB_N.brstm ./workdir.tmp/files/sound/strm/270_N.brstm
ln -f ./RetroRewind6/strm/gBC1_N.brstm ./workdir.tmp/files/sound/strm/271_N.brstm
ln -f ./RetroRewind6/strm/gBC2_N.brstm ./workdir.tmp/files/sound/strm/272_N.brstm
ln -f ./RetroRewind6/strm/gBC4_N.brstm ./workdir.tmp/files/sound/strm/274_N.brstm
ln -f ./RetroRewind6/strm/GCNBC_N.brstm ./workdir.tmp/files/sound/strm/276_N.brstm
ln -f ./RetroRewind6/strm/gcnGC_N.brstm ./workdir.tmp/files/sound/strm/277_N.brstm
ln -f ./RetroRewind6/strm/gcnPP_N.brstm ./workdir.tmp/files/sound/strm/278_N.brstm
ln -f ./RetroRewind6/strm/gcnBP_N.brstm ./workdir.tmp/files/sound/strm/279_N.brstm
ln -f ./RetroRewind6/strm/gcnBoC_N.brstm ./workdir.tmp/files/sound/strm/280_N.brstm
ln -f ./RetroRewind6/strm/dsbDS_N.brstm ./workdir.tmp/files/sound/strm/281_N.brstm
ln -f ./RetroRewind6/strm/dsPS_N.brstm ./workdir.tmp/files/sound/strm/283_N.brstm
ln -f ./RetroRewind6/strm/dsTT_N.brstm ./workdir.tmp/files/sound/strm/284_N.brstm
ln -f ./RetroRewind6/strm/dsWS_N.brstm ./workdir.tmp/files/sound/strm/285_N.brstm
ln -f ./RetroRewind6/strm/dsLA_N.brstm ./workdir.tmp/files/sound/strm/286_N.brstm
ln -f ./RetroRewind6/strm/dsTTC_N.brstm ./workdir.tmp/files/sound/strm/287_N.brstm
ln -f ./RetroRewind6/strm/wGC_N.brstm ./workdir.tmp/files/sound/strm/293_N.brstm
ln -f ./RetroRewind6/strm/wMMM_N.brstm ./workdir.tmp/files/sound/strm/294_N.brstm
ln -f ./RetroRewind6/strm/wCM_N.brstm ./workdir.tmp/files/sound/strm/295_N.brstm
ln -f ./RetroRewind6/strm/wRR_N.brstm ./workdir.tmp/files/sound/strm/296_N.brstm
ln -f ./RetroRewind6/strm/3dsHH_N.brstm ./workdir.tmp/files/sound/strm/297_N.brstm
ln -f ./RetroRewind6/strm/3dsSR_N.brstm ./workdir.tmp/files/sound/strm/298_N.brstm
ln -f ./RetroRewind6/strm/3dsDH_N.brstm ./workdir.tmp/files/sound/strm/299_N.brstm
ln -f ./RetroRewind6/strm/uACB_N.brstm ./workdir.tmp/files/sound/strm/300_N.brstm
ln -f ./RetroRewind6/strm/sBS_N.brstm ./workdir.tmp/files/sound/strm/301_N.brstm
ln -f ./RetroRewind6/strm/tPPB_N.brstm ./workdir.tmp/files/sound/strm/302_N.brstm
ln -f ./RetroRewind6/strm/dsNBB_N.brstm ./workdir.tmp/files/sound/strm/303_N.brstm
ln -f ./RetroRewind6/CT/Tracks/Z0.szs ./workdir.tmp/files/Race/Course/184.szs
ln -f ./RetroRewind6/CT/Tracks/Z1.szs ./workdir.tmp/files/Race/Course/185.szs
ln -f ./RetroRewind6/CT/Tracks/Z2.szs ./workdir.tmp/files/Race/Course/186.szs
ln -f ./RetroRewind6/CT/Tracks/Z3.szs ./workdir.tmp/files/Race/Course/187.szs
ln -f ./RetroRewind6/CT/Tracks/Z4.szs ./workdir.tmp/files/Race/Course/188.szs
ln -f ./RetroRewind6/CT/Tracks/Z5.szs ./workdir.tmp/files/Race/Course/189.szs
ln -f ./RetroRewind6/CT/Tracks/Z6.szs ./workdir.tmp/files/Race/Course/190.szs
ln -f ./RetroRewind6/CT/Tracks/Z7.szs ./workdir.tmp/files/Race/Course/191.szs
ln -f ./RetroRewind6/CT/Tracks/Z8.szs ./workdir.tmp/files/Race/Course/192.szs
ln -f ./RetroRewind6/CT/Tracks/Z9.szs ./workdir.tmp/files/Race/Course/193.szs
ln -f ./RetroRewind6/CT/Tracks/Z10.szs ./workdir.tmp/files/Race/Course/194.szs
ln -f ./RetroRewind6/CT/Tracks/Z11.szs ./workdir.tmp/files/Race/Course/195.szs
ln -f ./RetroRewind6/CT/Tracks/Z12.szs ./workdir.tmp/files/Race/Course/196.szs
ln -f ./RetroRewind6/CT/Tracks/Z13.szs ./workdir.tmp/files/Race/Course/197.szs
ln -f ./RetroRewind6/CT/Tracks/Z14.szs ./workdir.tmp/files/Race/Course/198.szs
ln -f ./RetroRewind6/CT/Tracks/Z15.szs ./workdir.tmp/files/Race/Course/199.szs
ln -f ./RetroRewind6/CT/Tracks/Z16.szs ./workdir.tmp/files/Race/Course/200.szs
ln -f ./RetroRewind6/CT/Tracks/Z17.szs ./workdir.tmp/files/Race/Course/201.szs
ln -f ./RetroRewind6/CT/Tracks/Z18.szs ./workdir.tmp/files/Race/Course/202.szs
ln -f ./RetroRewind6/CT/Tracks/Z19.szs ./workdir.tmp/files/Race/Course/203.szs
ln -f ./RetroRewind6/CT/Tracks/Z20.szs ./workdir.tmp/files/Race/Course/204.szs
ln -f ./RetroRewind6/CT/Tracks/Z21.szs ./workdir.tmp/files/Race/Course/205.szs
ln -f ./RetroRewind6/CT/Tracks/Z22.szs ./workdir.tmp/files/Race/Course/206.szs
ln -f ./RetroRewind6/CT/Tracks/Z23.szs ./workdir.tmp/files/Race/Course/207.szs
ln -f ./RetroRewind6/CT/Tracks/Z24.szs ./workdir.tmp/files/Race/Course/208.szs
ln -f ./RetroRewind6/CT/Tracks/Z25.szs ./workdir.tmp/files/Race/Course/209.szs
ln -f ./RetroRewind6/CT/Tracks/Z26.szs ./workdir.tmp/files/Race/Course/210.szs
ln -f ./RetroRewind6/CT/Tracks/Z27.szs ./workdir.tmp/files/Race/Course/211.szs
ln -f ./RetroRewind6/CT/Tracks/Z28.szs ./workdir.tmp/files/Race/Course/212.szs
ln -f ./RetroRewind6/CT/Tracks/Z29.szs ./workdir.tmp/files/Race/Course/213.szs
ln -f ./RetroRewind6/CT/Tracks/Z30.szs ./workdir.tmp/files/Race/Course/214.szs
ln -f ./RetroRewind6/CT/Tracks/Z31.szs ./workdir.tmp/files/Race/Course/215.szs
ln -f ./RetroRewind6/CT/Tracks/Z32.szs ./workdir.tmp/files/Race/Course/216.szs
ln -f ./RetroRewind6/CT/Tracks/Z33.szs ./workdir.tmp/files/Race/Course/217.szs
ln -f ./RetroRewind6/CT/Tracks/Z34.szs ./workdir.tmp/files/Race/Course/218.szs
ln -f ./RetroRewind6/CT/Tracks/Z35.szs ./workdir.tmp/files/Race/Course/219.szs
ln -f ./RetroRewind6/CT/Tracks/Z36.szs ./workdir.tmp/files/Race/Course/220.szs
ln -f ./RetroRewind6/CT/Tracks/Z37.szs ./workdir.tmp/files/Race/Course/221.szs
ln -f ./RetroRewind6/CT/Tracks/Z38.szs ./workdir.tmp/files/Race/Course/222.szs
ln -f ./RetroRewind6/CT/Tracks/Z39.szs ./workdir.tmp/files/Race/Course/223.szs
ln -f ./RetroRewind6/CT/Tracks/Z40.szs ./workdir.tmp/files/Race/Course/224.szs
ln -f ./RetroRewind6/CT/Tracks/Z41.szs ./workdir.tmp/files/Race/Course/225.szs
ln -f ./RetroRewind6/CT/Tracks/Z42.szs ./workdir.tmp/files/Race/Course/226.szs
ln -f ./RetroRewind6/CT/Tracks/Z43.szs ./workdir.tmp/files/Race/Course/227.szs
ln -f ./RetroRewind6/CT/Tracks/Z44.szs ./workdir.tmp/files/Race/Course/228.szs
ln -f ./RetroRewind6/CT/Tracks/Z45.szs ./workdir.tmp/files/Race/Course/229.szs
ln -f ./RetroRewind6/CT/Tracks/Z46.szs ./workdir.tmp/files/Race/Course/230.szs
ln -f ./RetroRewind6/CT/Tracks/Z47.szs ./workdir.tmp/files/Race/Course/231.szs
ln -f ./RetroRewind6/CT/Tracks/Z48.szs ./workdir.tmp/files/Race/Course/232.szs
ln -f ./RetroRewind6/CT/Tracks/Z49.szs ./workdir.tmp/files/Race/Course/233.szs
ln -f ./RetroRewind6/CT/Tracks/Z50.szs ./workdir.tmp/files/Race/Course/234.szs
ln -f ./RetroRewind6/CT/Tracks/Z51.szs ./workdir.tmp/files/Race/Course/235.szs
ln -f ./RetroRewind6/CT/Tracks/Z52.szs ./workdir.tmp/files/Race/Course/236.szs
ln -f ./RetroRewind6/CT/Tracks/Z53.szs ./workdir.tmp/files/Race/Course/237.szs
ln -f ./RetroRewind6/CT/Tracks/Z54.szs ./workdir.tmp/files/Race/Course/238.szs
ln -f ./RetroRewind6/CT/Tracks/Z55.szs ./workdir.tmp/files/Race/Course/239.szs
ln -f ./RetroRewind6/CT/Tracks/Z56.szs ./workdir.tmp/files/Race/Course/240.szs
ln -f ./RetroRewind6/CT/Tracks/Z57.szs ./workdir.tmp/files/Race/Course/241.szs
ln -f ./RetroRewind6/CT/Tracks/Z58.szs ./workdir.tmp/files/Race/Course/242.szs
ln -f ./RetroRewind6/CT/Tracks/Z59.szs ./workdir.tmp/files/Race/Course/243.szs
ln -f ./RetroRewind6/CT/Tracks/Z60.szs ./workdir.tmp/files/Race/Course/244.szs
ln -f ./RetroRewind6/CT/Tracks/Z61.szs ./workdir.tmp/files/Race/Course/245.szs
ln -f ./RetroRewind6/CT/Tracks/Z62.szs ./workdir.tmp/files/Race/Course/246.szs
ln -f ./RetroRewind6/CT/Tracks/Z63.szs ./workdir.tmp/files/Race/Course/247.szs
ln -f ./RetroRewind6/CT/Tracks/Z64.szs ./workdir.tmp/files/Race/Course/248.szs
ln -f ./RetroRewind6/CT/Tracks/Z65.szs ./workdir.tmp/files/Race/Course/249.szs
ln -f ./RetroRewind6/CT/Tracks/Z66.szs ./workdir.tmp/files/Race/Course/250.szs
ln -f ./RetroRewind6/CT/Tracks/Z67.szs ./workdir.tmp/files/Race/Course/251.szs
ln -f ./RetroRewind6/CT/Tracks/Z68.szs ./workdir.tmp/files/Race/Course/252.szs
ln -f ./RetroRewind6/CT/Tracks/Z69.szs ./workdir.tmp/files/Race/Course/253.szs
ln -f ./RetroRewind6/CT/Tracks/Z70.szs ./workdir.tmp/files/Race/Course/254.szs
ln -f ./RetroRewind6/CT/Tracks/Z71.szs ./workdir.tmp/files/Race/Course/255.szs
ln -f ./RetroRewind6/CT/Tracks/Z72.szs ./workdir.tmp/files/Race/Course/256.szs
ln -f ./RetroRewind6/CT/Tracks/Z73.szs ./workdir.tmp/files/Race/Course/257.szs
ln -f ./RetroRewind6/CT/Tracks/Z74.szs ./workdir.tmp/files/Race/Course/258.szs
ln -f ./RetroRewind6/CT/Tracks/Z75.szs ./workdir.tmp/files/Race/Course/259.szs
ln -f ./RetroRewind6/CT/Tracks/Z76.szs ./workdir.tmp/files/Race/Course/260.szs
ln -f ./RetroRewind6/CT/Tracks/Z77.szs ./workdir.tmp/files/Race/Course/261.szs
ln -f ./RetroRewind6/CT/Tracks/Z78.szs ./workdir.tmp/files/Race/Course/262.szs
ln -f ./RetroRewind6/CT/Tracks/Z79.szs ./workdir.tmp/files/Race/Course/263.szs
ln -f ./RetroRewind6/BT/Tracks/old_battle4_sfc.szs ./workdir.tmp/files/Race/Course/264.szs
ln -f ./RetroRewind6/BT/Tracks/sfcMC1.szs ./workdir.tmp/files/Race/Course/265.szs
ln -f ./RetroRewind6/BT/Tracks/sfcVL2.szs ./workdir.tmp/files/Race/Course/266.szs
ln -f ./RetroRewind6/BT/Tracks/n64BD.szs ./workdir.tmp/files/Race/Course/267.szs
ln -f ./RetroRewind6/BT/Tracks/n64BF.szs ./workdir.tmp/files/Race/Course/268.szs
ln -f ./RetroRewind6/BT/Tracks/old_matenro_64.szs ./workdir.tmp/files/Race/Course/269.szs
ln -f ./RetroRewind6/BT/Tracks/n64BB.szs ./workdir.tmp/files/Race/Course/270.szs
ln -f ./RetroRewind6/BT/Tracks/gBC1.szs ./workdir.tmp/files/Race/Course/271.szs
ln -f ./RetroRewind6/BT/Tracks/gBC2.szs ./workdir.tmp/files/Race/Course/272.szs
ln -f ./RetroRewind6/BT/Tracks/old_battle3_gba.szs ./workdir.tmp/files/Race/Course/273.szs
ln -f ./RetroRewind6/BT/Tracks/gBC4.szs ./workdir.tmp/files/Race/Course/274.szs
ln -f ./RetroRewind6/BT/Tracks/old_cookieland_gc.szs ./workdir.tmp/files/Race/Course/275.szs
ln -f ./RetroRewind6/BT/Tracks/GCNBC.szs ./workdir.tmp/files/Race/Course/276.szs
ln -f ./RetroRewind6/BT/Tracks/gcnGC.szs ./workdir.tmp/files/Race/Course/277.szs
ln -f ./RetroRewind6/BT/Tracks/gcnPP.szs ./workdir.tmp/files/Race/Course/278.szs
ln -f ./RetroRewind6/BT/Tracks/gcnBP.szs ./workdir.tmp/files/Race/Course/279.szs
ln -f ./RetroRewind6/BT/Tracks/gcnBoC.szs ./workdir.tmp/files/Race/Course/280.szs
ln -f ./RetroRewind6/BT/Tracks/dsbDS.szs ./workdir.tmp/files/Race/Course/281.szs
ln -f ./RetroRewind6/BT/Tracks/old_house_ds.szs ./workdir.tmp/files/Race/Course/282.szs
ln -f ./RetroRewind6/BT/Tracks/dsPS.szs ./workdir.tmp/files/Race/Course/283.szs
ln -f ./RetroRewind6/BT/Tracks/dsTT.szs ./workdir.tmp/files/Race/Course/284.szs
ln -f ./RetroRewind6/BT/Tracks/dsWS.szs ./workdir.tmp/files/Race/Course/285.szs
ln -f ./RetroRewind6/BT/Tracks/dsLA.szs ./workdir.tmp/files/Race/Course/286.szs
ln -f ./RetroRewind6/BT/Tracks/dsTTC.szs ./workdir.tmp/files/Race/Course/287.szs
ln -f ./RetroRewind6/BT/Tracks/block_battle.szs ./workdir.tmp/files/Race/Course/288.szs
ln -f ./RetroRewind6/BT/Tracks/venice_battle.szs ./workdir.tmp/files/Race/Course/289.szs
ln -f ./RetroRewind6/BT/Tracks/skate_battle.szs ./workdir.tmp/files/Race/Course/290.szs
ln -f ./RetroRewind6/BT/Tracks/casino_battle.szs ./workdir.tmp/files/Race/Course/291.szs
ln -f ./RetroRewind6/BT/Tracks/sand_battle.szs ./workdir.tmp/files/Race/Course/292.szs
ln -f ./RetroRewind6/BT/Tracks/wGC.szs ./workdir.tmp/files/Race/Course/293.szs
ln -f ./RetroRewind6/BT/Tracks/wMMM.szs ./workdir.tmp/files/Race/Course/294.szs
ln -f ./RetroRewind6/BT/Tracks/wCM.szs ./workdir.tmp/files/Race/Course/295.szs
ln -f ./RetroRewind6/BT/Tracks/wRR.szs ./workdir.tmp/files/Race/Course/296.szs
ln -f ./RetroRewind6/BT/Tracks/3dsHH.szs ./workdir.tmp/files/Race/Course/297.szs
ln -f ./RetroRewind6/BT/Tracks/3dsSR.szs ./workdir.tmp/files/Race/Course/298.szs
ln -f ./RetroRewind6/BT/Tracks/3dsDH.szs ./workdir.tmp/files/Race/Course/299.szs
ln -f ./RetroRewind6/BT/Tracks/uACB.szs ./workdir.tmp/files/Race/Course/300.szs
ln -f ./RetroRewind6/BT/Tracks/sBS.szs ./workdir.tmp/files/Race/Course/301.szs
ln -f ./RetroRewind6/BT/Tracks/tPPB.szs ./workdir.tmp/files/Race/Course/302.szs
ln -f ./RetroRewind6/BT/Tracks/dsNBB.szs ./workdir.tmp/files/Race/Course/303.szs
ln -f ./RetroRewind6/UI/Channel.szs ./workdir.tmp/files/Scene/UI/Channel.szs
ln -f ./RetroRewind6/UI/Globe.szs ./workdir.tmp/files/Scene/UI/Globe.szs
ln -f ./RetroRewind6/UI/MenuMulti.szs ./workdir.tmp/files/Scene/UI/MenuMulti.szs
ln -f ./RetroRewind6/UI/MenuSingle.szs ./workdir.tmp/files/Scene/UI/MenuSingle.szs
ln -f ./RetroRewind6/UI/Title.szs ./workdir.tmp/files/Scene/UI/Title.szs
ln -f ./RetroRewind6/UI/Title_U.szs ./workdir.tmp/files/Scene/UI/Title_E.szs
ln -f ./RetroRewind6/UI/Title_U.szs ./workdir.tmp/files/Scene/UI/Title_F.szs
ln -f ./RetroRewind6/UI/Title_U.szs ./workdir.tmp/files/Scene/UI/Title_G.szs
ln -f ./RetroRewind6/UI/Title_U.szs ./workdir.tmp/files/Scene/UI/Title_I.szs
ln -f ./RetroRewind6/UI/Title_U.szs ./workdir.tmp/files/Scene/UI/Title_S.szs
ln -f ./RetroRewind6/UI/Title_U.szs ./workdir.tmp/files/Scene/UI/Title_M.szs
ln -f ./RetroRewind6/UI/Title_U.szs ./workdir.tmp/files/Scene/UI/Title_Q.szs
ln -f ./RetroRewind6/UI/Title_U.szs ./workdir.tmp/files/Scene/UI/Title_U.szs
ln -f ./RetroRewind6/UI/Title_U.szs ./workdir.tmp/files/Scene/UI/Title_J.szs
ln -f ./extra/thp/banana.thp ./workdir.tmp/files/thp/course/cup_select.thp
ln -f ./extra/thp/banana.thp ./workdir.tmp/files/thp/course/banana.thp
ln -f ./extra/thp/banana.thp ./workdir.tmp/files/thp/course/flower.thp
ln -f ./extra/thp/banana.thp ./workdir.tmp/files/thp/course/kinoko.thp
ln -f ./extra/thp/banana.thp ./workdir.tmp/files/thp/course/kohona.thp
ln -f ./extra/thp/banana.thp ./workdir.tmp/files/thp/course/koura.thp
ln -f ./extra/thp/banana.thp ./workdir.tmp/files/thp/course/special.thp
ln -f ./extra/thp/banana.thp ./workdir.tmp/files/thp/course/star.thp
ln -f ./extra/thp/banana.thp ./workdir.tmp/files/thp/course/thunder.thp
ln -f ./extra/thp/banana.thp ./workdir.tmp/files/thp/battle/battle_cup_select.thp
ln -f ./extra/thp/banana.thp ./workdir.tmp/files/thp/battle/battle_retro.thp
ln -f ./extra/thp/banana.thp ./workdir.tmp/files/thp/battle/battle_wii.thp
ln -f ./extra/thp/banana.thp ./workdir.tmp/files/thp/battle/battle_select.thp
ln -f ./extra/thp/banana.thp ./workdir.tmp/files/thp/title/title.thp
ln -f ./extra/thp/banana.thp ./workdir.tmp/files/thp/title/title_50.thp
ln -f ./extra/thp/banana.thp ./workdir.tmp/files/thp/title/title_SD.thp
ln -f ./extra/thp/banana.thp ./workdir.tmp/files/thp/title/title_SD_50.thp
ln -f ./extra/thp/banana.thp ./workdir.tmp/files/thp/title/top_menu.thp
ln -f ./extra/thp/banana.thp ./workdir.tmp/files/thp/ending/ending_normal.thp
ln -f ./extra/thp/banana.thp ./workdir.tmp/files/thp/ending/ending_normal_50.thp
ln -f ./extra/thp/banana.thp ./workdir.tmp/files/thp/ending/ending_true.thp
ln -f ./extra/thp/banana.thp ./workdir.tmp/files/thp/ending/ending_true_50.thp
ln -f ./extra/thp/banana.thp ./workdir.tmp/files/thp/button/class_top.thp
ln -f ./extra/thp/banana.thp ./workdir.tmp/files/thp/button/drift_select.thp
ln -f ./extra/thp/banana.thp ./workdir.tmp/files/thp/button/indiv_team.thp
ln -f ./extra/thp/banana.thp ./workdir.tmp/files/thp/button/multi_top.thp
ln -f ./extra/thp/banana.thp ./workdir.tmp/files/thp/button/single_top.thp
ln -f ./extra/savebanner/savebanner.tpl ./workdir.tmp/files/Boot/savebanner.tpl
ln -f ./extra/Boot/Loaders/${SRC_TYPE}/Main.dol ./workdir.tmp/sys/
